### ISSUE TITLE
Inquiry on Internal and External Load Balancing（Static）in the Llumnix Project

### ISSUE THREAD

**Issue by Ronniexie** [AlibabaPAI/llumnix#59]
In Llumnix project, Llumnix has implemented static load balancing internally.

We would like to explore the following question: What is the difference between load balancing for inference services and load balancing through an external gateway (Envoy)? Specifically, where should we implement static load balancing?

Option 1: Delegate load balancing to the external gateway (Envoy) and let Llumnix handle dynamic scheduling. The advantage of this approach is modular decoupling.

Option 2: Implement static load balancing and dynamic migration scheduling within the inference service. What are the main advantages of this approach?

Thank you, we look forward to hearing your insights.

**Comment by zhypku** [comment]
The key principle or advantage of Llumnix's design is being close to inference engines; that is, Llumnix can talk with inference engines in a fine-grained, efficient manner thanks to the Ray-based architecture. Therefore, Llumnix can acquire information from inference engines, like real-time loads / requests, more accurately and timely. External gateways typically are not designed for this purpose. Ideally, Llumnix would deliver better scheduling efficiency than external gateways.

That being said, Llumnix provides the same interface as existing inference engines, so that it is compatible with external gateways.

In general, given that LLMs are highly dynamic, we believe that scheduling near to inference engines would be beneficial.
