### ISSUE TITLE
About integration with the newest vLLM

### ISSUE THREAD

**Issue by PanJason** [AlibabaPAI/llumnix#61]
Hi, I recently read the paper llumnix. I really like the idea. It is simple and working. I would like to ask whether llumnix can support the newest vLLM or not. If not, is there any doc which lists the interface change that is necessary for adopting the newest version?

**Comment by s5u13b** [comment]
Currently, llumnix cannot support the newest vLLM because vLLM has changed some interfaces and redesigned their engine architecture recently. However, llumnix is designed as a separate LLM scheduling stack on top of the backend LLM inference engine (the interfaces that interact with the backend engine are defined in the class `BackendInterface).` Therefore, adapting to the newest vLLM should not require much effort, and we are currently working on it.

**Comment by PanJason** [comment]
Thanks a lot for the reply! I have some further questions about llumnix and I can ask you offline.
